In [1]:
# from support.df_init import init

# df = init()
# df
import pandas as pd

df = pd.read_csv('pp_train.csv')
df

,originalTitle,rating,startYear,endYear,runtimeMinutes,awardWins,numVotes,totalImages,totalVideos,totalCredits,...,is_War,is_Horror,is_Animation,fill_runtimeMinutes,is_from_Oceania,is_from_North America,is_from_South America,is_from_Asia,is_from_Africa,is_from_Europe
0,Neogenic Nightmare Chapter 3: Hydro-Man,8,1995,1995.0,NaN,0.0,779,1,0,21,...,0,0,1,40.0,0,1,0,0,0,0
1,Looping,6,1982,1982.0,NaN,0.0,11,1,0,1,...,0,0,0,28.0,0,0,0,0,0,1
2,Idealnaya para,6,1992,1992.0,NaN,0.0,38,1,0,24,...,0,0,0,90.0,0,0,0,0,0,1
3,MasterChef Celebrity México,6,2021,NaN,NaN,0.0,15,22,0,56,...,0,0,0,31.0,0,1,0,0,0,0
4,Seutateueob,8,2020,2020.0,80.0,1.0,15718,347,2,47,...,0,0,0,80.0,0,0,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16426,Caprices,6,1942,1942.0,NaN,0.0,73,4,0,45,...,0,0,0,90.0,0,0,0,0,0,1
16427,Haar Jeet,5,1990,1990.0,NaN,0.0,15,2,0,22,...,0,0,0,90.0,0,0,0,1,0,0
16428,Kotigobba 3,6,2021,2021.0,140.0,0.0,2560,39,3,129,...,0,0,0,140.0,0,0,0,1,0,0
16429,Ator l'invincibile,4,1982,1982.0,NaN,0.0,3011,52,1,53,...,0,0,0,90.0,0,0,0,0,0,1
16430,Anniversary Night,10,2022,2022.0,NaN,0.0,9,7,0,19,...,0,0,0,12.0,0,0,0,1,0,0

In [2]:
og_df = pd.read_csv('dm1_dataset_2425_imdb/train.csv')
og_df

,originalTitle,rating,startYear,endYear,runtimeMinutes,awardWins,numVotes,worstRating,bestRating,totalImages,...,titleType,awardNominationsExcludeWins,canHaveEpisodes,isRatable,isAdult,numRegions,userReviewsTotal,ratingCount,countryOfOrigin,genres
0,Neogenic Nightmare Chapter 3: Hydro-Man,"(7, 8]",1995,\N,\N,0.0,779,1,10,1,...,tvEpisode,0,False,True,0,1,0,781,['US'],"Action,Adventure,Animation"
1,Looping,"(5, 6]",1982,\N,\N,0.0,11,1,10,1,...,videoGame,0,False,True,0,1,0,11,['XWG'],Action
2,Idealnaya para,"(5, 6]",1992,\N,\N,0.0,38,1,10,1,...,movie,0,False,True,0,1,1,38,['RU'],Comedy
3,MasterChef Celebrity México,"(5, 6]",2021,\N,\N,0.0,15,1,10,22,...,tvSeries,0,True,True,0,1,0,15,['MX'],Reality-TV
4,Seutateueob,"(7, 8]",2020,2020,80,1.0,15718,1,10,347,...,tvSeries,1,True,True,0,32,452,15746,['KR'],"Comedy,Drama,Romance"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16426,Caprices,"(5, 6]",1942,\N,\N,0.0,73,1,10,4,...,movie,0,False,True,0,14,4,73,['FR'],Comedy
16427,Haar Jeet,"(4, 5]",1990,\N,\N,0.0,15,1,10,2,...,movie,0,False,True,0,1,1,15,['IN'],"Action,Drama,Thriller"
16428,Kotigobba 3,"(5, 6]",2021,\N,140,0.0,2560,1,10,39,...,movie,5,False,True,0,5,49,2560,['IN'],"Action,Drama,Romance"
16429,Ator l'invincibile,"(3, 4]",1982,\N,\N,0.0,3011,1,10,52,...,movie,0,False,True,0,26,58,3012,['IT'],"Action,Adventure,Fantasy"
16430,Anniversary Night,"(9, 10]",2022,\N,\N,0.0,9,1,10,7,...,short,0,False,True,0,1,0,9,['IN'],"Drama,Short"

In [3]:
df['countryOfOrigin'] = og_df['countryOfOrigin']

In [4]:
train = df
test = pd.read_csv('pp_test.csv')
og_test = pd.read_csv('dm1_dataset_2425_imdb/test.csv')
test['countryOfOrigin'] = og_test['countryOfOrigin']
test

,originalTitle,rating,startYear,endYear,runtimeMinutes,awardWins,numVotes,totalImages,totalVideos,totalCredits,...,is_War,is_Comedy,fill_runtimeMinutes,is_from_South America,is_from_Oceania,is_from_Europe,is_from_Asia,is_from_Africa,is_from_North America,countryOfOrigin
0,Geologist of Animal Collective Performs Live a...,10,2015,2015.0,21.0,0.0,15,7,2,11,...,0,0,21.0,0,0,0,0,0,1,['US']
1,Shan gou 1999,5,1999,1999.0,NaN,0.0,304,10,0,40,...,0,0,91.0,0,0,0,1,0,0,['HK']
2,The Craftsman: Preserving the Last Higgins Boat,9,2023,2023.0,NaN,0.0,10,2,0,6,...,0,0,73.0,0,0,0,0,0,1,['US']
3,Week 3: Tuesday,7,2020,2020.0,NaN,0.0,11,0,0,52,...,0,0,33.0,0,0,1,0,0,0,['GB']
4,Traumhaus,6,1999,1999.0,90.0,0.0,145,2,0,44,...,0,0,90.0,0,0,1,0,0,0,['DE']
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5473,Parasiz yasamak pahali,8,1994,1994.0,141.0,0.0,45,1,0,12,...,0,1,141.0,0,0,0,1,0,0,['TR']
5474,Wedding Bell Blues,7,1994,1994.0,22.0,0.0,19,17,0,35,...,0,1,22.0,0,0,0,0,0,1,['US']
5475,O anthropos pou to 'paize poly!,4,1983,1983.0,85.0,0.0,14,1,0,30,...,0,1,85.0,0,0,1,0,0,0,['GR']
5476,Above Average Presents,7,2012,NaN,NaN,0.0,111,56,0,992,...,0,1,30.0,0,0,0,0,0,1,['US']
5477,Omae wa mada Gunma wo shiranai,5,2017,2017.0,30.0,0.0,11,1,0,17,...,0,1,30.0,0,0,0,1,0,0,['JP']

In [7]:
train.to_csv('pp_train.csv', index=False)
test.to_csv('pp_test.csv', index=False)

In [8]:
test.columns

Index(['originalTitle', 'rating', 'startYear', 'endYear', 'runtimeMinutes',
       'awardWins', 'numVotes', 'totalImages', 'totalVideos', 'totalCredits',
       'criticReviewsTotal', 'titleType', 'awardNominationsExcludeWins',
       'canHaveEpisodes', 'isAdult', 'numRegions', 'userReviewsTotal',
       'is_Western', 'is_Thriller', 'is_Horror', 'is_Animation', 'is_Family',
       'is_News', 'is_Sport', 'is_Reality-TV', 'is_Biography', 'is_Sci-Fi',
       'is_Fantasy', 'is_Documentary', 'is_Talk-Show', 'is_Drama', 'is_Music',
       'is_Game-Show', 'is_Adventure', 'is_Romance', 'is_Mystery', 'is_Short',
       'is_Action', 'is_Adult', 'is_History', 'is_Musical', 'is_Crime',
       'is_Film-Noir', 'is_War', 'is_Comedy', 'fill_runtimeMinutes',
       'is_from_South America', 'is_from_Oceania', 'is_from_Europe',
       'is_from_Asia', 'is_from_Africa', 'is_from_North America',
       'countryOfOrigin'],
      dtype='object')

In [1]:
from support.df_init import init

train = init()
test = init('pp_test.csv')
train, test

(                                 originalTitle  rating  startYear  endYear  \
 0      Neogenic Nightmare Chapter 3: Hydro-Man       8       1995   1995.0
 1                                      Looping       6       1982   1982.0
 2                               Idealnaya para       6       1992   1992.0
 3                  MasterChef Celebrity México       6       2021      NaN
 4                                  Seutateueob       8       2020   2020.0
 ...                                        ...     ...        ...      ...
 16426                                 Caprices       6       1942   1942.0
 16427                                Haar Jeet       5       1990   1990.0
 16428                              Kotigobba 3       6       2021   2021.0
 16429                       Ator l'invincibile       4       1982   1982.0
 16430                        Anniversary Night      10       2022   2022.0

        runtimeMinutes  awardWins  numVotes  totalImages  totalVideos  \
 0                 NaN        0.0       779            1            0
 1                 NaN        0.0        11            1            0
 2                 NaN        0.0        38            1            0
 3                 NaN        0.0        15           22            0
 4                80.0        1.0     15718          347            2
 ...               ...        ...       ...          ...          ...
 16426             NaN        0.0        73            4            0
 16427             NaN        0.0        15            2            0
 16428           140.0        0.0      2560           39            3
 16429             NaN        0.0      3011           52            1
 16430             NaN        0.0         9            7            0

        totalCredits  ...  is_Horror is_Animation  fill_runtimeMinutes  \
 0                21  ...          0            1                 40.0
 1                 1  ...          0            0                 28.0
 2                24  ...          0            0                 90.0
 3                56  ...          0            0                 31.0
 4                47  ...          0            0                 80.0
 ...             ...  ...        ...          ...                  ...
 16426            45  ...          0            0                 90.0
 16427            22  ...          0            0                 90.0
 16428           129  ...          0            0                140.0
 16429            53  ...          0            0                 90.0
 16430            19  ...          0            0                 12.0

        is_from_Oceania  is_from_North America  is_from_South America  \
 0                    0                      1                      0
 1                    0                      0                      0
 2                    0                      0                      0
 3                    0                      1                      0
 4                    0                      0                      0
 ...                ...                    ...                    ...
 16426                0                      0                      0
 16427                0                      0                      0
 16428                0                      0                      0
 16429                0                      0                      0
 16430                0                      0                      0

        is_from_Asia  is_from_Africa  is_from_Europe  countryOfOrigin
 0                 0               0               0             [US]
 1                 0               0               1            [XWG]
 2                 0               0               1             [RU]
 3                 0               0               0             [MX]
 4                 1               0               0             [KR]
 ...             ...             ...             ...              ...
 16426             0               0               1             [FR]
 16427             1               0               0             [IN]
 16428             1               0               0             [IN]
 16429             0               0               1             [IT]
 16430             1               0               0             [IN]

 [16431 rows x 53 columns],
                                           originalTitle  rating  startYear  \
 0     Geologist of Animal Collective Performs Live a...      10       2015
 1                                         Shan gou 1999       5       1999
 2       The Craftsman: Preserving the Last Higgins Boat       9       2023
 3                                       Week 3: Tuesday       7       2020
 4                                             Traumhaus       6       1999
 ...                                                 ...     ...        ...
 5473                             Parasiz yasamak pahali       8       1994
 5474                                 Wedding Bell Blues       7       1994
 5475                    O anthropos pou to 'paize poly!       4       1983
 5476                             Above Average Presents       7       2012
 5477                     Omae wa mada Gunma wo shiranai       5       2017

       endYear  runtimeMinutes  awardWins  numVotes  totalImages  totalVideos  \
 0      2015.0            21.0        0.0        15            7            2
 1      1999.0             NaN        0.0       304           10            0
 2      2023.0             NaN        0.0        10            2            0
 3      2020.0             NaN        0.0        11            0            0
 4      1999.0            90.0        0.0       145            2            0
 ...       ...             ...        ...       ...          ...          ...
 5473   1994.0           141.0        0.0        45            1            0
 5474   1994.0            22.0        0.0        19           17            0
 5475   1983.0            85.0        0.0        14            1            0
 5476      NaN             NaN        0.0       111           56            0
 5477   2017.0            30.0        0.0        11            1            0

       totalCredits  ...  is_War is_Comedy  fill_runtimeMinutes  \
 0               11  ...       0         0                 21.0
 1               40  ...       0         0                 91.0
 2                6  ...       0         0                 73.0
 3               52  ...       0         0                 33.0
 4               44  ...       0         0                 90.0
 ...            ...  ...     ...       ...                  ...
 5473            12  ...       0         1                141.0
 5474            35  ...       0         1                 22.0
 5475            30  ...       0         1                 85.0
 5476           992  ...       0         1                 30.0
 5477            17  ...       0         1                 30.0

       is_from_South America  is_from_Oceania  is_from_Europe  is_from_Asia  \
 0                         0                0               0             0
 1                         0                0               0             1
 2                         0                0               0             0
 3                         0                0               1             0
 4                         0                0               1             0
 ...                     ...              ...             ...           ...
 5473                      0                0               0             1
 5474                      0                0               0             0
 5475                      0                0               1             0
 5476                      0                0               0             0
 5477                      0                0               0             1

       is_from_Africa  is_from_North America  countryOfOrigin
 0                  0                      1             [US]
 1                  0                      0             [HK]
 2                  0                      1             [US]
 3                  0                      0             [GB]
 4                  0                      0             [DE]
 ...              ...                    ...              ...
 5473               0                      0             [TR]
 5474               0                      1             [US]
 5475               0                      0             [GR]
 5476               0                      1             [US]
 5477               0                      0             [JP]

 [5478 rows x 53 columns])

In [3]:
from support.countries_handling import init_countries_trn_tst

train, test = init_countries_trn_tst(train, test)

In [4]:
train.columns

Index(['originalTitle', 'rating', 'startYear', 'endYear', 'runtimeMinutes',
       'awardWins', 'numVotes', 'totalImages', 'totalVideos', 'totalCredits',
       'criticReviewsTotal', 'titleType', 'awardNominationsExcludeWins',
       'canHaveEpisodes', 'isAdult', 'numRegions', 'userReviewsTotal',
       'is_Documentary', 'is_History', 'is_Adventure', 'is_Thriller',
       'is_Game-Show', 'is_Comedy', 'is_Sci-Fi', 'is_Romance', 'is_Biography',
       'is_Musical', 'is_Western', 'is_Music', 'is_Film-Noir', 'is_Adult',
       'is_Reality-TV', 'is_News', 'is_Action', 'is_Crime', 'is_Short',
       'is_Fantasy', 'is_Family', 'is_Mystery', 'is_Talk-Show', 'is_Drama',
       'is_Sport', 'is_War', 'is_Horror', 'is_Animation',
       'fill_runtimeMinutes', 'is_from_Oceania', 'is_from_North America',
       'is_from_South America', 'is_from_Asia', 'is_from_Africa',
       'is_from_Europe', 'countryOfOrigin', 'countryOfOrigin_freq_enc',
       'countryOfOrigin_NA', 'countryOfOrigin_AF', 'countryOfOrigin_AS',
       'countryOfOrigin_EU', 'countryOfOrigin_OC', 'countryOfOrigin_SA',
       'countryOfOrigin_UNK'],
      dtype='object')

In [5]:
train['countryOfOrigin_freq_enc'].unique()

array([3.97061279e-01, 1.35247955e-02, 7.95903601e-03, 1.36361106e-02,
       9.18350309e-03, 4.70863249e-02, 9.85139422e-03, 3.42850782e-02,
       1.32465075e-02, 4.68636946e-02, 6.73456893e-03, 4.59731730e-02,
       9.87922302e-02, 1.83670062e-03, 6.40062337e-03, 7.23548728e-04,
       5.06484110e-03, 2.79401124e-02, 9.51744866e-03, 3.06116770e-03,
       7.51377525e-03, 1.75321423e-02, 6.28930818e-03, 2.82184004e-02,
       6.94606779e-02, 4.31624645e-01, 4.45260756e-04, 1.66972783e-03,
       3.45633662e-02, 2.34875049e-02, 1.45822898e-02, 1.80887182e-02,
       4.56392275e-03, 4.95853509e-01, 1.11315189e-04, 3.00551010e-03,
       1.04079702e-02, 5.94979685e-02, 1.44709746e-03, 3.45077086e-03,
       1.01853398e-02, 1.22446708e-03, 4.11866199e-03, 9.89592030e-02,
       8.23732398e-03, 1.93688429e-02, 6.67891134e-04, 2.56024935e-03,
       1.01074192e-01, 4.03461902e-01, 1.33355596e-01, 3.89603161e-04,
       1.00183670e-03, 5.67707464e-03, 5.17615629e-03, 4.89230255e-02,
       9.40613347e-03, 1.12428341e-01, 3.20587744e-02, 4.31346357e-01,
       1.28012467e-03, 1.08198364e-01, 1.62520176e-02, 3.17248289e-02,
       5.51010185e-03, 6.12233539e-04, 1.19663828e-02, 4.60288306e-02,
       8.05365392e-02, 4.39694996e-03, 1.30238771e-02, 8.29854734e-02,
       6.70674013e-02, 8.90521512e-04, 1.99810764e-02, 5.22624812e-02,
       4.20938387e-01, 7.84772082e-03, 4.17821562e-01, 4.34129237e-03,
       1.54895085e-01, 4.76874269e-01, 1.50275505e-03, 4.14593421e-01,
       1.07975733e-01, 1.08309679e-01, 2.64373574e-02, 1.12984917e-02,
       2.78287972e-04, 3.61774364e-03, 1.76434574e-02, 1.87009517e-02,
       1.66972783e-04, 5.00918350e-04, 4.03795848e-01, 2.94985251e-03,
       5.54906217e-02, 1.33578227e-03, 4.78710970e-01, 5.51010185e-02,
       3.33945567e-04, 2.22630378e-04, 1.04357990e-01, 6.40618912e-02,
       7.83102354e-02, 5.03701230e-02, 3.99677186e-01, 5.09489620e-01,
       4.20548784e-01, 1.48605777e-02, 5.36706184e-01, 3.75132187e-02,
       6.35053153e-02, 4.43034452e-01, 4.05020315e-01, 2.50459175e-03,
       4.60844882e-02, 2.43780264e-02, 3.88490009e-02, 4.44147604e-01,
       5.49897033e-02, 5.50787555e-01, 5.56575945e-05, 1.39143986e-03,
       2.24300106e-02, 4.59564758e-01, 2.61590694e-03, 1.44765403e-01,
       4.02293093e-01, 2.42667112e-02, 1.53614961e-01, 4.15149997e-01,
       1.12261368e-01, 4.10697390e-01, 4.90120777e-01, 1.56954416e-02,
       9.23916068e-03, 5.53793065e-02, 1.67640675e-01, 4.01513887e-01,
       4.98580731e-01, 1.08643624e-01, 5.50453609e-02, 4.06578728e-01,
       2.63260422e-02, 4.18545110e-02, 3.05560194e-02, 1.01519452e-01,
       5.56575945e-04, 1.07029554e-01, 3.60661212e-02, 3.46746814e-02,
       4.06912673e-01, 3.23370624e-02, 4.61123170e-01, 1.61407024e-02,
       1.78994824e-01, 7.12417209e-03, 4.26003228e-01, 4.37468693e-02,
       1.82556910e-02, 7.57499861e-02, 1.64746480e-02, 2.65486726e-02,
       3.87376858e-02, 1.16324372e-01, 4.54833862e-01, 4.23554294e-01,
       7.39132855e-02, 9.15567429e-02, 1.08420994e-01, 2.72722213e-03,
       4.25001391e-01, 2.73835365e-02, 4.48210608e-01, 2.88306339e-02,
       4.54722547e-02, 4.10586074e-01, 1.33077308e-01, 5.27077420e-02,
       1.19107252e-02, 5.31697000e-01, 6.95719931e-03, 7.24105304e-02,
       1.48939723e-01, 3.98397061e-01, 4.77542161e-02, 2.35431625e-02,
       1.05749430e-03, 4.14370791e-01, 3.98731007e-01, 8.51561196e-03,
       4.65965381e-01, 5.41826682e-01, 1.12317026e-01, 8.16496911e-02,
       1.01296822e-02, 8.18723215e-02, 3.70123003e-02, 1.79440085e-01,
       5.03812545e-01, 3.30049535e-02, 3.09456225e-02, 4.15762231e-02,
       4.61958034e-03, 3.31162687e-02, 8.71041354e-02, 1.40368453e-01,
       7.90337842e-03, 1.05192854e-01, 5.28747148e-03, 4.61401458e-02,
       5.76390048e-01, 4.08526743e-02, 8.14270607e-02, 6.04330161e-01,
       1.79217454e-02, 3.78471642e-03, 1.23559860e-02, 1.91851728e-01,
       7.22992152e-02, 4.76985585e-02, 1.58290199e-01, 1.26732343e-01,
       1.51110369e-01, 3.99565871e-01, 1.41926866e-02, 4.00011132e-01,
       8.12600879e-03, 1.82000334e-02, 5.00918350e-02, 1.03857071e-01,
       6.67891134e-03, 4.02738354e-01, 9.38387043e-02, 9.01653031e-03,
       6.90154172e-02, 5.14276173e-02, 4.41921300e-02, 2.38771080e-02,
       4.66967218e-02, 1.44932376e-01, 3.97784828e-01, 3.16135137e-02,
       5.05370958e-02, 2.02593644e-02, 6.03328324e-02, 8.40429677e-03,
       3.52869149e-02, 5.63811432e-02, 3.98897980e-01, 4.95909167e-01,
       1.02465631e-01, 4.02126120e-01, 1.07419157e-02, 1.01352480e-01,
       1.79328769e-01, 4.05298603e-01, 3.97339567e-01, 4.00679023e-01,
       9.35047587e-03, 3.97116937e-01, 2.00367340e-03, 5.30416875e-01,
       8.01469360e-03, 8.75493961e-02, 1.04024044e-01, 3.98285746e-01,
       3.08899649e-02, 5.11493293e-02, 5.39322090e-02, 6.22251906e-02,
       4.01458229e-01, 3.97172594e-01, 6.99615963e-02, 2.76061669e-02,
       1.06862581e-02, 4.60844882e-02, 1.81777704e-01, 1.00684588e-01,
       1.62854121e-01, 4.15929204e-01, 4.45260756e-01, 1.51444315e-01,
       4.38359214e-01, 5.52123337e-02, 8.45995436e-03, 1.99254188e-02,
       1.03133523e-01, 4.63627762e-02, 5.72104414e-01, 2.83853732e-03,
       1.20888295e-01, 1.81443758e-02, 5.27633996e-02, 4.34685813e-02,
       1.50219847e-01, 1.06639951e-01, 4.81994768e-02, 3.28936383e-02,
       1.00294985e-01, 5.71046919e-02, 1.35247955e-02, 6.23365058e-03,
       2.47119719e-02, 4.02571381e-01, 2.91645795e-02, 4.07580564e-01,
       1.45878555e-01, 4.40808148e-01, 2.22630378e-03, 7.10190906e-02,
       3.48973117e-02, 5.66037736e-02, 1.17994100e-02, 2.18734346e-02,
       1.80330606e-02, 4.64740914e-02, 5.03144654e-02, 3.74575611e-02,
       1.92018701e-02, 3.73462459e-02, 5.08098180e-01, 9.68442144e-03,
       3.48416541e-02, 6.41008516e-01, 1.03189180e-01, 5.66594312e-02,
       3.99788501e-01, 5.69377192e-02, 1.73651695e-02, 1.37474258e-02,
       9.45622530e-02, 1.14598987e-01, 1.70312239e-02, 3.70679579e-02,
       4.07246619e-01, 3.97729170e-01, 2.56024935e-02, 4.39694996e-02,
       1.06306005e-02, 3.62887516e-02, 7.94790449e-02, 5.09378305e-01,
       1.38531753e-01, 1.05526799e-01, 3.99621528e-02, 1.45266322e-02,
       4.26337174e-02, 4.72032059e-01, 1.46379473e-02, 3.13352257e-02,
       4.60288306e-02, 7.50264374e-02, 4.10196471e-02, 1.05749430e-02,
       6.58429343e-01, 1.05081538e-01, 4.94239439e-02, 2.92758947e-02,
       3.57878332e-02, 4.49156787e-01, 5.38208939e-02, 3.67340124e-02,
       1.58123226e-01, 8.23732398e-03, 4.84221072e-02, 4.44147604e-02,
       5.93866533e-02, 7.94233873e-02, 3.54538877e-02, 1.10758613e-02,
       4.21884566e-02, 4.12144487e-01, 3.96282073e-02, 9.51744866e-03,
       4.07469249e-01, 1.01742083e-01, 3.97339567e-01, 3.98341404e-01,
       4.40808148e-02, 3.06116770e-03, 5.33144098e-01, 4.04909000e-01,
       4.20771414e-02, 1.36082819e-01, 7.68074804e-03, 6.88484444e-02,
       5.32921467e-01, 4.38080926e-01, 7.05738298e-02, 5.33199755e-02,
       8.06478544e-02, 2.13168587e-02, 6.66777982e-02, 6.45628096e-03,
       4.06244782e-01, 1.30238771e-02, 5.47114154e-02, 1.90794234e-01,
       3.42294206e-02, 2.81627428e-02, 2.38214504e-02, 5.42104970e-02,
       4.62236322e-01, 4.37134747e-01, 2.78287972e-02, 2.10385707e-02,
       2.42110536e-02, 2.78844548e-02, 4.56559248e-01, 4.33850949e-01,
       4.47487060e-02, 3.50086269e-02, 3.47303390e-02, 1.66972783e-02,
       8.73824233e-03, 6.16686147e-02, 2.30979017e-02, 3.33388991e-02,
       4.52217955e-01, 2.04819948e-02, 9.89035454e-02, 8.89964936e-02,
       4.25224022e-02, 1.43596594e-02, 1.20276062e-01, 2.29309289e-02,
       7.55273557e-02, 7.95903601e-02, 2.20960650e-02, 4.30233205e-02,
       1.14487672e-01, 1.50832081e-02, 4.00512050e-01, 6.57872767e-02,
       3.81811098e-02, 5.55351478e-01, 4.20159181e-01, 4.01625202e-01,
       1.07196527e-01, 1.66471865e-01, 4.93404575e-01, 5.01363611e-01,
       2.84410308e-02, 4.48266266e-01, 2.98881282e-02, 1.33466912e-01,
       4.01402571e-01, 1.80998497e-01, 5.32643179e-02, 2.54355207e-02,
       5.23793622e-01, 1.72538543e-03, 8.96087271e-02, 8.02025936e-02,
       7.09634330e-02, 4.38637502e-01, 7.29114488e-02, 1.01797740e-01,
       8.33194189e-02, 1.98141036e-02, 4.62792898e-01, 9.29481828e-03,
       2.03873769e-01, 4.00066789e-01, 1.94801581e-03, 1.52279178e-01,
       5.81621862e-02, 4.09305950e-01, 1.72538543e-03, 4.48488896e-01,
       5.80508710e-02, 4.48099293e-01, 4.21828909e-01, 7.87554962e-02,
       4.50826515e-03, 9.30594980e-02, 3.99621528e-01, 1.01575110e-01,
       1.90905549e-02, 1.34691379e-02, 6.51750431e-02, 3.95168921e-03,
       5.89970501e-03, 4.55112150e-01, 4.43257082e-01, 1.51054711e-01,
       2.04931263e-01, 5.43774698e-02, 8.54900651e-02, 3.89046585e-02,
       4.55167808e-01, 3.98508376e-02, 8.17610063e-02, 2.89419491e-03,
       3.61774364e-02, 6.18355875e-02, 1.22279735e-01, 3.72905883e-02,
       4.45260756e-03, 7.76980019e-02, 8.68258474e-02, 3.61217788e-02,
       4.73590471e-01, 4.33628319e-01, 4.26893750e-02, 4.66521957e-01,
       3.48416541e-02, 3.46190238e-02, 4.31735960e-01, 7.39132855e-02,
       4.91456559e-02, 8.13714031e-02, 5.58245673e-02, 3.53425725e-02,
       5.64089720e-01])